### ISSUE TITLE
Getting contacts from Access Token

### ISSUE THREAD

**Issue by peddinti** [aliang/google_contacts_api#19]
Hi,

I am using GoogleOauth2 strategy in my application and upon authentication, the strategy is giving me OauthHash with access_token and refresh_token. I am not sure how to proceed with using that data to get contacts. the contacts API is asking for OAuth2::AccessToken object but i am getting Omniauth::AuthHash from strategy. Any idea how to get the same?

**Comment by aliang** [comment]
The access token is in the credentials hash in the `Omniauth::AuthHash`. There's a constructor in the OAuth2 library for building an `OAuth2::AccessToken` from that string (and other attributes), the `#from_hash` method. (See https://github.com/intridea/omniauth/wiki/Auth-Hash-Schema and https://github.com/intridea/oauth2/blob/master/lib/oauth2/access_token.rb)

Since this question is really about OmniAuth and OAuth2, I'm closing this issue. If you need more help, please ask on StackOverflow or elsewhere instead. Thanks!
